version: "3.9"
services:
  docstream:
    build: 
      context: docstream
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "python app.py" 
  embeddings:
    build:
      context: embeddings
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/embeddings/
      - ./.cache/torch/:/.cache/torch/
      - ./.cache/huggingface/:/.cache/huggingface/
    ports:
      - "8000:8000"
    restart: always
    # uncomment to deploy on GPU
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
    command: sh -c "
      gunicorn --workers 1 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:8000"
  procstream:
    build:
      context: procstream
      dockerfile: Dockerfile
    env_file:
      - .env
    # embedding service needs to load first
    # note first time embedding service runs it will take a while to download the model
    # and this may fail, run it again and it should work
    command: sh -c "sleep 10; python app.py"
  chatbot:
    build:
      context: chatbot
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./models/:/models/
    ports:
      - "7860:7860"
    command: sh -c "python app.py"
